<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Quantitative explanatory variable with quantitative confounding variable | Causality and Multiple Regression Supplement</title>
  <meta name="description" content="This is a supplement for MA206 Probability and Statistics, West Point, NY." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Quantitative explanatory variable with quantitative confounding variable | Causality and Multiple Regression Supplement" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a supplement for MA206 Probability and Statistics, West Point, NY." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Quantitative explanatory variable with quantitative confounding variable | Causality and Multiple Regression Supplement" />
  
  <meta name="twitter:description" content="This is a supplement for MA206 Probability and Statistics, West Point, NY." />
  

<meta name="author" content="Krista Watts and Kevin Cummiskey" />


<meta name="date" content="2021-05-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="references.html"/>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro Stats Supplement</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#goals-of-quantitative-research-describe-predict-cause-and-effect"><i class="fa fa-check"></i><b>1.1</b> Goals of quantitative research (describe, predict, cause-and-effect)</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#validity"><i class="fa fa-check"></i><b>1.2</b> Validity</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="causality.html"><a href="causality.html"><i class="fa fa-check"></i><b>2</b> Causality</a>
<ul>
<li class="chapter" data-level="2.1" data-path="causality.html"><a href="causality.html#what-does-it-mean-for-one-thing-to-cause-another"><i class="fa fa-check"></i><b>2.1</b> What does it mean for one thing to cause another</a></li>
<li class="chapter" data-level="2.2" data-path="causality.html"><a href="causality.html#randomized-controlled-experiments"><i class="fa fa-check"></i><b>2.2</b> Randomized controlled experiments</a></li>
<li class="chapter" data-level="2.3" data-path="causality.html"><a href="causality.html#observational-studies-and-confounding"><i class="fa fa-check"></i><b>2.3</b> Observational Studies and Confounding</a></li>
<li class="chapter" data-level="2.4" data-path="causality.html"><a href="causality.html#causal-diagrams"><i class="fa fa-check"></i><b>2.4</b> Causal Diagrams</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="causality.html"><a href="causality.html#confounding-variable"><i class="fa fa-check"></i><b>2.4.1</b> Confounding variable</a></li>
<li class="chapter" data-level="2.4.2" data-path="causality.html"><a href="causality.html#collider"><i class="fa fa-check"></i><b>2.4.2</b> Collider</a></li>
<li class="chapter" data-level="2.4.3" data-path="causality.html"><a href="causality.html#mediator"><i class="fa fa-check"></i><b>2.4.3</b> Mediator</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html"><i class="fa fa-check"></i><b>3</b> Confounding adjustment with regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#categorical-confounding-variable"><i class="fa fa-check"></i><b>3.1</b> Categorical confounding variable</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#unadjusted-effect-of-x-on-y"><i class="fa fa-check"></i><b>3.1.1</b> Unadjusted effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="3.1.2" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#effect-of-x-on-y-adjusting-for-c"><i class="fa fa-check"></i><b>3.1.2</b> Effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> adjusting for <span class="math inline">\(C\)</span></a></li>
<li class="chapter" data-level="3.1.3" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#assessing-model-adequacy"><i class="fa fa-check"></i><b>3.1.3</b> Assessing model adequacy</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#quantitative-confounding-variable"><i class="fa fa-check"></i><b>3.2</b> Quantitative confounding variable</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#unadjusted-effect-of-x-on-y-1"><i class="fa fa-check"></i><b>3.2.1</b> Unadjusted effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="3.2.2" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#effect-of-x-on-y-adjusting-for-c-1"><i class="fa fa-check"></i><b>3.2.2</b> Effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> adjusting for <span class="math inline">\(C\)</span></a></li>
<li class="chapter" data-level="3.2.3" data-path="confounding-adjustment-with-regression.html"><a href="confounding-adjustment-with-regression.html#assessing-model-adequacy-1"><i class="fa fa-check"></i><b>3.2.3</b> Assessing model adequacy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interactions.html"><a href="interactions.html"><i class="fa fa-check"></i><b>4</b> Interactions</a></li>
<li class="chapter" data-level="5" data-path="activity.html"><a href="activity.html"><i class="fa fa-check"></i><b>5</b> Activity</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="6" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><i class="fa fa-check"></i><b>6</b> Quantitative explanatory variable with quantitative confounding variable</a>
<ul>
<li class="chapter" data-level="6.1" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#unadjusted-effect-of-x-on-y-2"><i class="fa fa-check"></i><b>6.1</b> Unadjusted effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="6.2" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#effect-of-x-on-y-adjusting-for-c-2"><i class="fa fa-check"></i><b>6.2</b> Effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> adjusting for <span class="math inline">\(C\)</span></a></li>
<li class="chapter" data-level="6.3" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#assessing-model-adequacy-2"><i class="fa fa-check"></i><b>6.3</b> Assessing model adequacy</a></li>
<li class="chapter" data-level="6.4" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#r-markdown"><i class="fa fa-check"></i><b>6.4</b> R Markdown</a></li>
<li class="chapter" data-level="6.5" data-path="quantitative-explanatory-variable-with-quantitative-confounding-variable.html"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#including-plots"><i class="fa fa-check"></i><b>6.5</b> Including Plots</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Causality and Multiple Regression Supplement</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="quantitative-explanatory-variable-with-quantitative-confounding-variable" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Quantitative explanatory variable with quantitative confounding variable</h1>
<p>Confounding variables can, of course, be quantitative as well. Here we will explore the situation where you have a quantitative treatment variable <span class="math inline">\((X)\)</span>, a quantitative response variable <span class="math inline">\((Y)\)</span>, and a quantitative confounding variable <span class="math inline">\((C)\)</span>. In fact, the ice cream example from the chapter 4 was just such a situation.</p>
<div id="unadjusted-effect-of-x-on-y-2" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Unadjusted effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span></h2>
<p>The file wage_data.csv on the course website contains a subset of wage data from the Center for Economic and Policy Research. It includes individual annual income from wages and salary (Earnings) for people who are above the poverty line but below the “top 2%.” [Do you think I should cite info for poverty line and top 2%?] We wish to explore the relationship between family size and earnings. A scatterplot indicates that there does appear to be a positive relationship between the two variables.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb1-1" aria-hidden="true" tabindex="-1"></a>wage_dat<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">&quot;wage_data.csv&quot;</span>)</span>
<span id="cb1-2"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb1-2" aria-hidden="true" tabindex="-1"></a>wage_dat<span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>FamilySize, <span class="at">y=</span>Earnings))<span class="sc">+</span></span>
<span id="cb1-4"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb1-5"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Family Size&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Annual Earnings&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Family Size versus Annual Earnings&quot;</span>)</span></code></pre></div>
<p><img src="MA206supplement_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>If we were to consider only the treatment variable FamilySize and the response variable Earnings, we could use the following regression equation:
<span class="math display">\[\widehat{Earnings} = \beta_0+\beta_1*FamilySize\]</span>
Fitting this in R, we get the following results:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb2-1" aria-hidden="true" tabindex="-1"></a>size_mod <span class="ot">=</span> <span class="fu">lm</span>(Earnings<span class="sc">~</span>FamilySize, <span class="at">data =</span> wage_dat)</span>
<span id="cb2-2"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(size_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Earnings ~ FamilySize, data = wage_dat)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -41825 -28222 -13021  13383 141580 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    49013       4212  11.636  &lt; 2e-16 ***
## FamilySize      4802       1272   3.775 0.000179 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 39120 on 498 degrees of freedom
## Multiple R-squared:  0.02782,    Adjusted R-squared:  0.02587 
## F-statistic: 14.25 on 1 and 498 DF,  p-value: 0.0001792</code></pre>
<p>We see that there is a very significant effect of family size on earnings; for every additional member of the family, we expect to earn about $48702 more.</p>
</div>
<div id="effect-of-x-on-y-adjusting-for-c-2" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> adjusting for <span class="math inline">\(C\)</span></h2>
<p>However, there are a number of factors that are related to both earnings and family size, perhaps in a causal way. We will look at age. We expect to earn more as we age and get more experience in the workforce and possibly even more education. We also expect that, in general, family size will increase - or at least stay the same - as we get older. We can visually inspect our data to check this. Below is a graph of earnings versus age.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-1" aria-hidden="true" tabindex="-1"></a>wage_dat<span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Age</span><span class="st">`</span>,</span>
<span id="cb4-3"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y=</span><span class="st">`</span><span class="at">Earnings</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb4-4"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb4-5"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="MA206supplement_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Age is a potential <em>confounder</em>. When we add age to the model with family size, we have the following regression model:</p>
<p><span class="math display">\[\widehat{Earnings}=\beta_0+\beta_1*FamilySize+\beta_2*Age\]</span>
When we estimate the coefficents for this model in R, we get the following results.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb5-1" aria-hidden="true" tabindex="-1"></a>size_age_mod <span class="ot">=</span> <span class="fu">lm</span>(Earnings<span class="sc">~</span>FamilySize<span class="sc">+</span>Age, <span class="at">data =</span> wage_dat)</span>
<span id="cb5-2"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(size_age_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Earnings ~ FamilySize + Age, data = wage_dat)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -48975 -26711 -12103  14107 145564 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  26643.8     8322.0   3.202  0.00145 ** 
## FamilySize    5534.1     1283.0   4.314 1.94e-05 ***
## Age            449.7      144.7   3.107  0.00199 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38790 on 497 degrees of freedom
## Multiple R-squared:  0.04635,    Adjusted R-squared:  0.04251 
## F-statistic: 12.08 on 2 and 497 DF,  p-value: 7.551e-06</code></pre>
<p>We see that there is still a significant positive effect of family size on earnings, although it’s magnitude is slightly larger. We expect to earn about $5534 less per year for every additional member of the family <em>after adjusting for age</em>. We also note that the coefficient for age is 449.7, meaning that, for every year older a person is, we expect them to earn $450 more on average, after adjusting for family size. Of course, the relationship between family size and earnings is a complex one that would require a much more extensive analysis to fully understand.</p>
</div>
<div id="assessing-model-adequacy-2" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Assessing model adequacy</h2>
<p>Just like with previous regression models, these results might not mean much if our validity conditions aren’t met.</p>
<p>Here, we may be willing to believe that our assumption of independence is met by the way the data was collected. The CEPR data is from the Current Population Survey’s Annual Social and Economic Supplement (CPS ASEC or March Supplement). Surveyors use a random sample to survey about 60,000 occupied households by both telephone and in person surveys. Households come from all 50 states and the District of Columbia and are only in the sample pool for a limited time. Since respondents responses to survey questions are not dependent on another respondents, independence can be assumed.</p>
<p>To check for linearity and equal variance, we can plot the predicted values vs. the residuals.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-1" aria-hidden="true" tabindex="-1"></a>size_age_mod<span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fortify</span>(wage_dat)<span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid))<span class="sc">+</span></span>
<span id="cb7-4"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb7-5"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb7-6"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>( <span class="at">x =</span> <span class="st">&quot;Predicted Values&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Residuals vs. predicted values&quot;</span>)</span></code></pre></div>
<p><img src="MA206supplement_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The linearity and constant variance conditions appear to be met. Although we have some large positive residuals, there does not appear to be a pattern and the width is relatively constant.</p>
<p>Our histogram, however, shows that the residuals seem to be skewed relatively heavily to the right. Our fourth validity condition, normality of the residuals, is likely not met. Although we can be comfortable in our estimates of the regression coefficients, we should be careful about drawing any conclusions about their statistical significance. (For a much more in depth assumption about assessing model adequacy, to include methods to handle violations of the validity conditions, take MA376!)</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="quantitative-explanatory-variable-with-quantitative-confounding-variable.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(size_age_mod<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="MA206supplement_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>

</div>
<div id="r-markdown" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> R Markdown</h2>
</div>
<div id="including-plots" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Including Plots</h2>

<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-carver2016guidelines" class="csl-entry">
Carver, Robert, Michelle Everson, John Gabrosek, Nicholas Horton, Robin Lock, Megan Mocko, Allan Rossman, et al. 2016. <span>“Guidelines for Assessment and Instruction in Statistics Education (GAISE) College Report 2016.”</span>
</div>
<div id="ref-cummiskey2020causal" class="csl-entry">
Cummiskey, Kevin, Bryan Adams, James Pleuss, Dusty Turner, Nicholas Clark, and Krista Watts. 2020. <span>“Causal Inference in Introductory Statistics Courses.”</span> <em>Journal of Statistics Education</em> 28 (1): 2–8.
</div>
<div id="ref-hernan2019second" class="csl-entry">
Hernán, Miguel A, John Hsu, and Brian Healy. 2019. <span>“A Second Chance to Get Causal Inference Right: A Classification of Data Science Tasks.”</span> <em>Chance</em> 32 (1): 42–49.
</div>
<div id="ref-horton2015challenges" class="csl-entry">
Horton, Nicholas J. 2015. <span>“Challenges and Opportunities for Statistics and Statistical Education: Looking Back, Looking Forward.”</span> <em>The American Statistician</em> 69 (2): 138–45.
</div>
<div id="ref-kaplan2018teaching" class="csl-entry">
Kaplan, Daniel. 2018. <span>“Teaching Stats for Data Science.”</span> <em>The American Statistician</em> 72 (1): 89–96.
</div>
<div id="ref-lubke2020we" class="csl-entry">
Lübke, Karsten, Matthias Gehrke, Jörg Horst, and Gero Szepannek. 2020. <span>“Why We Should Teach Causal Inference: Examples in Linear Regression with Simulated Data.”</span> <em>Journal of Statistics Education</em> 28 (2): 133–39.
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="references.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MA206supplement.pdf", "MA206supplement.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
